# Generated by Django 5.2.13 on 2026-04-11 00:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("action_type", models.CharField(max_length=100)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ManualRecurringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("summary_template", models.TextField(blank=True)),
                ("event_url", models.URLField(blank=True)),
                ("source_page", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly_nth_weekday", "Monthly nth weekday"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True, help_text="0=Monday, 6=Sunday", null=True
                    ),
                ),
                (
                    "week_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="1,2,3,4 or -1 for last. Only used for monthly_nth_weekday.",
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ManualSingleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("event_url", models.URLField(blank=True)),
                ("source_page", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="RecurringException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occurrence_date", models.DateField()),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("cancel_occurrence", "Cancel occurrence"),
                            ("override_occurrence", "Override occurrence"),
                        ],
                        max_length=30,
                    ),
                ),
                ("override_title", models.CharField(blank=True, max_length=255)),
                ("override_start_time", models.TimeField(blank=True, null=True)),
                ("override_end_time", models.TimeField(blank=True, null=True)),
                ("override_venue", models.CharField(blank=True, max_length=255)),
                ("override_city", models.CharField(blank=True, max_length=100)),
                ("override_state", models.CharField(blank=True, max_length=50)),
                ("override_location", models.CharField(blank=True, max_length=255)),
                ("override_categories", models.JSONField(blank=True, default=list)),
                ("override_summary", models.TextField(blank=True)),
                ("override_notes", models.TextField(blank=True)),
                (
                    "recurring_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="events.manualrecurringevent",
                    ),
                ),
            ],
            options={
                "ordering": ["occurrence_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recurring_event", "occurrence_date"),
                        name="unique_recurring_exception_per_day",
                    )
                ],
            },
        ),
    ]
