# Generated by Django 5.2.13 on 2026-04-13 23:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_page", models.URLField(blank=True)),
                ("event_url", models.URLField(blank=True)),
                (
                    "external_event_id",
                    models.CharField(
                        blank=True,
                        help_text="Source-specific event ID if available.",
                        max_length=500,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                (
                    "relevance_status",
                    models.CharField(
                        choices=[
                            ("relevant", "Relevant"),
                            ("irrelevant", "Irrelevant"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="uncertain",
                        max_length=20,
                    ),
                ),
                ("relevance_reason", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("approved", "Approved"),
                            ("corrected", "Corrected"),
                            ("hidden", "Hidden"),
                            ("canceled", "Canceled"),
                            ("duplicate", "Duplicate"),
                            ("bad_scrape", "Bad Scrape"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_datetime", "title"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("events_found", models.IntegerField(default=0)),
                ("relevant_count", models.IntegerField(default=0)),
                ("irrelevant_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapedEventOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("cancel", "Cancel"),
                            ("hide", "Hide"),
                            ("mark_irrelevant", "Mark Irrelevant"),
                            ("mark_duplicate", "Mark Duplicate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("override_title", models.CharField(blank=True, max_length=500)),
                (
                    "override_start_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("override_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("override_venue", models.CharField(blank=True, max_length=255)),
                ("override_city", models.CharField(blank=True, max_length=100)),
                ("override_state", models.CharField(blank=True, max_length=50)),
                ("override_location", models.CharField(blank=True, max_length=500)),
                ("override_categories", models.JSONField(blank=True, default=list)),
                ("override_summary", models.TextField(blank=True)),
                ("override_event_url", models.URLField(blank=True)),
                ("override_source_page", models.URLField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scraped_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override",
                        to="events.scrapedevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="scrapedevent",
            name="scrape_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scraped_events",
                to="events.scraperun",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapedevent",
            index=models.Index(
                fields=["source_name", "external_event_id"],
                name="events_scra_source__6d6402_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapedevent",
            index=models.Index(
                fields=["start_datetime"], name="events_scra_start_d_d82179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapedevent",
            index=models.Index(
                fields=["review_status"], name="events_scra_review__9ec7a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapedevent",
            index=models.Index(
                fields=["relevance_status"], name="events_scra_relevan_e0f346_idx"
            ),
        ),
    ]
