# Generated by Django 5.2.13 on 2026-04-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_scrapedevent_scraperun_scrapedeventoverride_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(blank=True)),
                (
                    "extractor_key",
                    models.CharField(
                        choices=[
                            ("auto_calendar_check", "Auto calendar check"),
                            ("zephyr", "Zephyr Wine Bar"),
                            ("midtown", "Midtown Spirits"),
                            ("max_casino", "Max Casino"),
                            ("fixed_events", "Fixed Events File"),
                            ("manual_placeholders", "Manual Placeholders"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
