# Generated by Django 5.2.13 on 2026-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_scrapesource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapesource",
            name="extractor_key",
            field=models.CharField(
                choices=[
                    ("auto_calendar_check", "Auto calendar check"),
                    ("zephyr", "Zephyr Wine Bar"),
                    ("midtown", "Midtown Spirits"),
                    ("max_casino", "Max Casino"),
                ],
                max_length=50,
            ),
        ),
    ]
