# Generated by Django 5.2.13 on 2026-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_scrapesource_extractor_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrecurringevent',
            name='anchor_date',
            field=models.DateField(blank=True, help_text="Used for 'Every X weeks'. This date controls the recurrence rhythm.", null=True),
        ),
        migrations.AddField(
            model_name='manualrecurringevent',
            name='interval_weeks',
            field=models.PositiveIntegerField(default=1, help_text="Used only for 'Every X weeks'. Example: 2 means every other week."),
        ),
        migrations.AlterField(
            model_name='manualrecurringevent',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly_weekday', 'Monthly by weekday'), ('weekly_interval', 'Every X weeks')], default='weekly', max_length=50),
        ),
    ]
