# Generated by Django 5.2.13 on 2026-05-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_manualrecurringevent_anchor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualrecurringevent',
            name='week_of_month',
            field=models.IntegerField(blank=True, help_text='1,2,3,4,5 or -1 for last. Only used for Monthly by weekday.', null=True),
        ),
        migrations.AlterField(
            model_name='manualrecurringevent',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week.', null=True),
        ),
    ]
